// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDtHkAzpusfXjSpbflaM1WdyoH7GD6poU',
    appId: '1:1086339369048:web:d5684e14cf21219181622d',
    messagingSenderId: '1086339369048',
    projectId: 'techyvivekraj-54ef6',
    authDomain: 'techyvivekraj-54ef6.firebaseapp.com',
    storageBucket: 'techyvivekraj-54ef6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjjQpEqk09KbyoGrDvXl6KPx0FOfL132I',
    appId: '1:1086339369048:android:4d197d05fef5a3f081622d',
    messagingSenderId: '1086339369048',
    projectId: 'techyvivekraj-54ef6',
    storageBucket: 'techyvivekraj-54ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwIC62Mt_VVmYyxWLwlVKXxDy1lB6Ja8',
    appId: '1:1086339369048:ios:956656b1096b8f8b81622d',
    messagingSenderId: '1086339369048',
    projectId: 'techyvivekraj-54ef6',
    storageBucket: 'techyvivekraj-54ef6.appspot.com',
    iosBundleId: 'com.example.hospitalLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwIC62Mt_VVmYyxWLwlVKXxDy1lB6Ja8',
    appId: '1:1086339369048:ios:956656b1096b8f8b81622d',
    messagingSenderId: '1086339369048',
    projectId: 'techyvivekraj-54ef6',
    storageBucket: 'techyvivekraj-54ef6.appspot.com',
    iosBundleId: 'com.example.hospitalLocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDtHkAzpusfXjSpbflaM1WdyoH7GD6poU',
    appId: '1:1086339369048:web:7597f36f9f475c1381622d',
    messagingSenderId: '1086339369048',
    projectId: 'techyvivekraj-54ef6',
    authDomain: 'techyvivekraj-54ef6.firebaseapp.com',
    storageBucket: 'techyvivekraj-54ef6.appspot.com',
  );

}